Update default role policy
serverless-components/AwsLambda pull request #45
Opened 2021-04-07 15:02 UTC by alisalahio

closes https://github.com/serverless/components/issues/918#issuecomment-814418217

2021-04-12 10:20 UTC, MattiaPette requested changes

2021-04-12 10:20 UTC, MattiaPette commented on serverless.component.yml
> +version: 3.0.0
I think this should not be a major release, maybe a patch is a better fit?

2021-04-12 12:07 UTC, alisalahio commented
I'm not sure about how it should be done, but this is [how it was done](https://github.com/serverless-components/express/pull/70/commits/3f6ca759c2ee5121386477398d1f67a00ca3b05b) by the express component that had the same issue. Possibly because it's a breaking change..

Are you sure I should change it?

2021-04-12 16:54 UTC, Bappy0X commented
Any idea how long this PR could take? Can this be fixed locally in the time being?

2021-04-17 22:13 UTC, janpio commented
This currently leads to the normal "Deploy Lambda" getting started project on https://app.serverless.com/ being broken :/

2021-04-19 03:39 UTC, mthan160 commented
> This currently leads to the normal "Deploy Lambda" getting started project on https://app.serverless.com/ being broken :/
> 
> Update: As a hack I published `component: aws-lambda-fixed` based on this PR and this seems to allow me to deploy to Lambda.

Yes I can confirm that, it's broken because of this.

2021-04-19 11:25 UTC, janpio commented
If you are using that example, is says `component: aws-lamda` in the `serverless.yml`. Components seem to be downloaded on runtime, and not part of your node_modules if I got that right - which is why I published the `aws-lambda-fixed` package to that serverless components registry. (But I am also super green in all of this, so 🤷 if this is the right way to do this)

2021-04-19 12:22 UTC, LukeFerris commented
@janpio - thanks! I'm a Serverless beginner and there's nothing quite like following the default flow and it throwing an error you don't understand. I changed the serverless.yml to your update and it deployed successfully. I am in your debt.

If I've understood correctly, this is a breaking bug for all new lambda components? (including new, easily confused people like me). Is there some way we can increase the priority for the merge?

2021-04-20 18:36 UTC, eahefnawy approved these changes
Thanks for this fix @alisalahio! 🙌

2021-04-20 18:36 UTC, merged

2021-04-21 09:18 UTC, eahefnawy commented
This is now published! Thanks all!